# Generated by Django 5.2.7 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(db_column='ID_Admin', primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(db_column='ID_Usuario')),
                ('cargo', models.CharField(db_column='Cargo', max_length=50, null=True)),
                ('credenciales', models.CharField(db_column='Credenciales', max_length=100, null=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
    ]
