# Generated by Django 5.2.7 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(db_column='ID_Documento', primary_key=True, serialize=False)),
                ('archivo', models.CharField(db_column='Archivo', max_length=200, null=True)),
                ('fecha_subida', models.DateField(db_column='FechaSubida', null=True)),
                ('id_medico', models.IntegerField(db_column='ID_Medico', null=True)),
                ('id_tipo_documento', models.IntegerField(db_column='ID_TipoDocumento', null=True)),
                ('estado', models.CharField(db_column='Estado', max_length=20)),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(db_column='ID_TipoDocumento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, null=True)),
                ('descripcion', models.TextField(db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidacionDocumento',
            fields=[
                ('id_validacion', models.AutoField(db_column='ID_Validacion', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='Estado', max_length=20, null=True)),
                ('observaciones', models.TextField(db_column='Observaciones', null=True)),
                ('fecha_validacion', models.DateField(db_column='FechaValidacion', null=True)),
                ('id_documento', models.IntegerField(db_column='ID_Documento', null=True)),
                ('id_admin', models.IntegerField(db_column='ID_Admin', null=True)),
            ],
            options={
                'db_table': 'validacion_documento',
                'managed': False,
            },
        ),
    ]
