# Generated by Django 5.2.7 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(db_column='ID_Agenda', primary_key=True, serialize=False)),
                ('id_medico', models.IntegerField(db_column='ID_Medico')),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.TimeField(db_column='Hora')),
                ('disponible', models.BooleanField(db_column='Disponible', default=True)),
            ],
            options={
                'db_table': 'Agenda',
                'managed': False,
            },
        ),
    ]
