# Generated by Django 5.2.7 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(db_column='ID_Paciente', primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(db_column='ID_Usuario', unique=True)),
                ('grupo_sanguineo', models.CharField(db_column='GrupoSanguineo', max_length=5, null=True)),
                ('seguro_medico', models.CharField(db_column='SeguroMedico', max_length=100, null=True)),
                ('contacto_emergencia', models.CharField(db_column='ContactoEmergencia', max_length=100, null=True)),
                ('telefono_emergencia', models.CharField(db_column='TelefonoEmergencia', max_length=20, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
    ]
