# Generated by Django 5.2.7 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiccionarioMedico',
            fields=[
                ('id_termino', models.AutoField(db_column='ID_Termino', primary_key=True, serialize=False)),
                ('termino', models.CharField(db_column='Termino', max_length=100)),
                ('definicion', models.TextField(db_column='Definicion')),
                ('causas', models.TextField(db_column='Causas')),
                ('tratamientos', models.TextField(db_column='Tratamientos')),
            ],
            options={
                'db_table': 'Diccionario_Medico',
                'managed': False,
            },
        ),
    ]
