# Generated by Django 5.2.7 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(db_column='ID_Cita', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='Estado', max_length=20)),
                ('id_paciente', models.IntegerField(db_column='ID_Paciente')),
                ('id_medico', models.IntegerField(db_column='ID_Medico')),
                ('id_agenda', models.IntegerField(db_column='ID_Agenda')),
                ('motivo_consulta', models.TextField(db_column='MotivoConsulta', null=True)),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
    ]
